# Generated by Django 6.0.6 on 2026-06-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('text', models.TextField(verbose_name='Текст нотатки')),
                ('reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Час нагадування')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
